name: Build and Deploy Documentation to GitHub Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install mkdocs dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install -r requirements-docs.txt
          echo "✓ Dependencies installed successfully"

      - name: Build documentation with mkdocs
        run: |
          mkdocs build -v
          echo "✓ Documentation built successfully"
          ls -lh site/index.html

      - name: Upload documentation artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'site'
          name: 'github-pages'

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
